dependencies:
  # -organization/repo@<version>
  - smartcontractkit/chainlink-brownie-contracts@0.4.2
compiler:
  solc:
    remappings:
      - "@chainlink=smartcontractkit/chainlink-brownie-contracts@0.4.2"
dotenv: .env

networks:
  rinkeby:
    eth-usd-priceFeed: "0x8A753747A1Fa494EC906cE90E9f37563A8AF630e"
    verify: "True"
  development:
    verify: "False"
